# Generated by Django 5.2.6 on 2025-11-19 16:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BMIRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('weight_kg', models.FloatField(help_text='Weight in kilograms')),
                ('height_m', models.FloatField(help_text='Height in metres')),
                ('bmi_value', models.FloatField()),
                ('category', models.CharField(max_length=20)),
                ('original_weight_unit', models.CharField(choices=[('kg', 'Kilograms'), ('lb', 'Pounds')], max_length=5)),
                ('original_height_unit', models.CharField(choices=[('m', 'Metres'), ('cm', 'Centimetres'), ('ft_in', 'Feet/Inches')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bmi_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
